# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/profane',
                'doc_host': 'https://gngdb.github.io',
                'git_url': 'https://github.com/gngdb/profane',
                'lib_path': 'profane'},
  'syms': {'profane.core': {'profane.core.foo': ('core.html#foo', 'profane/core.py')}}}
